### ISSUE TITLE
Novi h/f, MakoLab

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rv-renault-header-footer-cro-slo-srb#7]
Joža,
ovo su novi h/f koji će vrijediti od 01.10.
https://export-rsi.makolab.net/Slovenia/index.html
https://dsi-export.makolab.pl/Slovenia/index.html
https://export-rsi.makolab.net/Croatia/index.html
https://dsi-export.makolab.pl/croatia/index.html

Kaže Ante da su takvi u BiH. Kako bi bilo najbolje da Ante to riješi na nekom "testu" i da onda stavimo u produkciju 01.10. ili u pon kad će trebati?

Btw. trebat će mi i upute kako će netko "drugi" moći importati na neke svoje stranice te naše h/f...

Tnx,
Saša.

**Comment by sasadj1** [comment]
@antesto2 samo da te assigneam na issue kad sam već sve napisao :)

**Comment by antesto2** [comment]
Josipe samo da javim da mozemo ovo rijesiti onako kako smo se jutros dogovorili, ja ih lokalno rijesim (mogu ih testirat lokalno) pa ti javim kad zavrsim da mozes povuc novi json
Sam dizajn mi izgleda 99% isti kao na BIH, imat cemo mozda neke sitne promjene ali koliko zasad vidim to ce vrijediti za sve zemlje

**Comment by jzlimen** [comment]
Pišem da imamo za arhivu. Ovo je riješeno, pozivanje H/F poziva se ovako:

![image](https://user-images.githubusercontent.com/16623112/193606290-46af9d63-11a5-4763-9219-800183a71bb3.png)

**Comment by sasadj1** [comment]
Evo i tekst:
```
<div id="rna-header"></div>
<div id="rna-footer"></div>
<script src="https://rna.sto2.hr/headers-footers/renault/hr/main.js" defer></script>
```

Jerbo ja ovo gore vidim kao fotku...
