### ISSUE TITLE
[Renault / Dacia; Slo / Hrv] Izmjena layouta headera i footera

### ISSUE THREAD

**Issue by sasadj1** [wssto2/rv-renault-header-footer-cro-slo-srb#8]
Grga,

slobodno možeš, kad stigneš, napraviti sve izmjene na h/f za R i D. Znači na stranicama: 
1. https://izaberiiodvezi.renault.hr/ treba biti ovaj: https://www.renault.hr/
2. https://izaberiiodvezi.dacia.hr/ treba biti ovaj: https://www.dacia.hr/
3. https://izberiinodpelji.dacia.si/ treba biti ovaj: https://www.dacia.si/
4. https://izberiinodpelji.renault.si/ treba biti ovaj: https://www.renault.si/

Rekao sam im da smo gotovi kroz cca. 10 radnih dana.

Tnx,
Saša

**Comment by gborac** [comment]
Riješeno
